    LOAD  #1,R1
    LOAD  #2,R2
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
    FMA   R2,R1
        FMA   R2,R1
    FMA   R2,R1
    WINT
    HALT
    